name: Latest FAQs YouTube Videos
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:
permissions:
      contents: write

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLOJR6EhNalnt0x--jh2P2qh-3YyPGWYh9,https://www.youtube.com/feeds/videos.xml?playlist_id=PLOJR6EhNalnuheSznhxBdwJBq7Ts4ELlZ"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          comment_tag_name: "FAQS"
          date_format: "mmm d, yyyy"
          template: '<table><tr><td><a href="$url"><img width="140px" src="http://img.youtube.com/vi/$videoId/maxresdefault.jpg"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
          committer_email: "alwinjohn231@gmail.com"
