name: Defronix Latest YouTube Videos
on:
  schedule:
    # Runs every minutes, on the hour
    - cron: "*/1 * * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch and insert videos from Playlist 1
        id: PLOJR6EhNalnu7hgxu7QhA9GrF9i23JX9A
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLOJR6EhNalnu7hgxu7QhA9GrF9i23JX9A"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/,playlistTitle/title"
          date_format: "mmm d, yyyy"
          template: |
            $playlistTitle
            <table>
            <tr>
            <td><a href="$url"><img width="140px" src="http://img.youtube.com/vi/$videoId/maxresdefault.jpg"></a></td>
            <td><a href="$url">$title</a><br/>$date</td>
            </tr>
            </table>$newline


name: OSINT
on:
  schedule:
    # Runs every minutes, on the hour
    - cron: "*/1 * * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch and insert videos from Playlist 2
        id: PLOJR6EhNalnvp092-sA_LWbqQsJHavUK2
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLOJR6EhNalnvp092-sA_LWbqQsJHavUK2"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/,playlistTitle/title"
          date_format: "mmm d, yyyy"
          template: |
            $playlistTitle
            <table>
            <tr>
            <td><a href="$url"><img width="140px" src="http://img.youtube.com/vi/$videoId/maxresdefault.jpg"></a></td>
            <td><a href="$url">$title</a><br/>$date</td>
            </tr>
            </table>$newline
