name: Defronix Latest YouTube Videos
on:
  schedule:
    # Runs every minutes, on the hour
    - cron: "*/1 * * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch and insert videos from Playlist 1
        id: playlist_1
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLOJR6EhNalnvUXy1RQL5DWxIj7KdCJBmq"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/,playlistTitle/title"
          date_format: "mmm d, yyyy"
          template: |
            # $playlistTitle
            <table>
            <tr>
            <td><a href="$url"><img width="140px" src="http://img.youtube.com/vi/$videoId/maxresdefault.jpg"></a></td>
            <td><a href="$url">$title</a><br/>$date</td>
            </tr>
            </table>$newline
      - name: Fetch and insert videos from Playlist 2
        id: playlist_2
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLOJR6EhNalnsQNexfdDn3DgKxUvIgTpDK"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/,playlistTitle/title"
          date_format: "mmm d, yyyy"
          template: |
            # $playlistTitle
            <table>
            <tr>
            <td><a href="$url"><img width="140px" src="http://img.youtube.com/vi/$videoId/maxresdefault.jpg"></a></td>
            <td><a href="$url">$title</a><br/>$date</td>
            </tr>
            </table>$newline

      # Fetch and insert videos from Playlist 3
      - name: Fetch and insert videos from Playlist 3
        id: playlist_3
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLOJR6EhNalnsj_PIenPD7LF3TnTZujasb"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/,playlistTitle/title"
          date_format: "mmm d, yyyy"
          template: |
            # $playlistTitle
            <table>
            <tr>
            <td><a href="$url"><img width="140px" src="http://img.youtube.com/vi/$videoId/maxresdefault.jpg"></a></td>
            <td><a href="$url">$title</a><br/>$date</td>
            </tr>
            </table>$newline

      # Fetch and insert videos from Playlist 4
      - name: Fetch and insert videos from Playlist 4
        id: playlist_4
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLOJR6EhNalnthGdlZwnRwlHk4L3mTgQHD"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/,playlistTitle/title"
          date_format: "mmm d, yyyy"
          template: |
            # $playlistTitle
            <table>
            <tr>
            <td><a href="$url"><img width="140px" src="http://img.youtube.com/vi/$videoId/maxresdefault.jpg"></a></td>
            <td><a href="$url">$title</a><br/>$date</td>
            </tr>
            </table>$newline

      # Fetch and insert videos from Playlist 5
      - name: Fetch and insert videos from Playlist 5
        id: playlist_5
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLOJR6EhNalnu7wxeH4suOSLMdGPAYHoqm"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/,playlistTitle/title"
          date_format: "mmm d, yyyy"
          template: |
            # $playlistTitle
            <table>
            <tr>
            <td><a href="$url"><img width="140px" src="http://img.youtube.com/vi/$videoId/maxresdefault.jpg"></a></td>
            <td><a href="$url">$title</a><br/>$date</td>
            </tr>
            </table>$newline

      # Fetch and insert videos from Playlist 6
      - name: Fetch and insert videos from Playlist 6
        id: playlist_6
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLOJR6EhNalnu5bVVqtOauOuv4bVhtQZdf"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/,playlistTitle/title"
          date_format: "mmm d, yyyy"
          template: |
            # $playlistTitle
            <table>
            <tr>
            <td><a href="$url"><img width="140px" src="http://img.youtube.com/vi/$videoId/maxresdefault.jpg"></a></td>
            <td><a href="$url">$title</a><br/>$date</td>
            </tr>
            </table>$newline

      # Fetch and insert videos from Playlist 7
      - name: Fetch and insert videos from Playlist 7
        id: playlist_7
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?playlist_id=PLOJR6EhNalnu-ESDmxURAtE2s9bNzWPfj"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/,playlistTitle/title"
          date_format: "mmm d, yyyy"
          template: |
            # $playlistTitle
            <table>
            <tr>
            <td><a href="$url"><img width="140px" src="http://img.youtube.com/vi/$videoId/maxresdefault.jpg"></a></td>
            <td><a href="$url">$title</a><br/>$date</td>
            </tr>
            </table>$newline
